// Detector is intentionally conservative (see the TODO in rtapDetect.ts) —
// these tests pin down "no signal → isRtap:false" as much as the positive
// matches, since silence is the overwhelmingly common case.
import { describe, expect, it } from 'vitest';
import { detectRtapFeed } from '../rtapDetect';
import type { BuilderSignals } from '../gtfsParse';
import type { FeedInfo, Agency } from '../../types/gtfs';

const AGENCY = (overrides: Partial<Agency> = {}): Agency => ({
  agency_id: 'a1',
  agency_name: 'Anytown Transit',
  agency_url: 'https://anytowntransit.example.org',
  agency_timezone: 'America/Denver',
  ...overrides,
});

const FEED_INFO = (overrides: Partial<FeedInfo> = {}): FeedInfo => ({
  feed_publisher_name: 'Anytown Transit',
  feed_publisher_url: 'https://anytowntransit.example.org',
  feed_lang: 'en-US',
  ...overrides,
});

// The exact structural signature confirmed against a real National RTAP GTFS
// Builder export (Skyline Bus / Big Sky MT — see rtapDetect.ts TODO): every
// core file BOM-prefixed, shapes.txt present but zero data rows, and the full
// optional-column checklist present as headers.
const RTAP_STRUCTURAL_SIGNATURE: BuilderSignals = {
  hasUtf8Bom: true,
  shapesFileHeaderOnly: true,
  emitsAllOptionalColumns: true,
};

// Mirrors tests/fixtures/sample-gtfs-feed: no BOM, real shape geometry, and
// several optional columns (zone_id, continuous_pickup/drop_off, …) absent
// entirely rather than present-but-empty.
const ORDINARY_STRUCTURAL_SIGNATURE: BuilderSignals = {
  hasUtf8Bom: false,
  shapesFileHeaderOnly: false,
  emitsAllOptionalColumns: false,
};

describe('detectRtapFeed', () => {
  it('defaults to isRtap:false with no signals when nothing is RTAP-branded', () => {
    const result = detectRtapFeed(FEED_INFO(), [AGENCY()]);
    expect(result).toEqual({ isRtap: false, confidence: 'low', signals: [] });
  });

  it('handles null/undefined feed_info and empty agencies without throwing', () => {
    expect(detectRtapFeed(null, [])).toEqual({ isRtap: false, confidence: 'low', signals: [] });
    expect(detectRtapFeed(undefined, [])).toEqual({ isRtap: false, confidence: 'low', signals: [] });
  });

  it('flags high confidence on an exact "National RTAP" mention in feed_publisher_name', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'National RTAP' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
    expect(result.signals.length).toBeGreaterThan(0);
  });

  it('flags high confidence on a nationalrtap.org URL', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_url: 'https://www.nationalrtap.org/gtfs' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
  });

  it('flags high confidence when the signal is on agency.txt rather than feed_info.txt', () => {
    const result = detectRtapFeed(null, [AGENCY({ agency_url: 'https://nationalrtap.org' })]);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
  });

  it('flags low confidence on a bare "RTAP" mention without the full org name/domain', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_version: 'built with RTAP tools' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('low');
  });

  it('flags low confidence on a "GTFS Builder" mention', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'Generated by GTFS Builder' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('low');
  });

  it('does not false-positive on unrelated substrings', () => {
    // "rtap" must be a whole word — shouldn't match inside an unrelated token.
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'Startapp Transit Co' }), []);
    expect(result.isRtap).toBe(false);
  });

  // ── Structural signature (real RTAP sample had NO string mention at all) ──
  describe('structural fallback', () => {
    it('fires low confidence on the confirmed RTAP structural signature even with zero string mentions', () => {
      // Mirrors the real Skyline Bus (Big Sky, MT) National RTAP GTFS Builder
      // export: fully agency-branded feed_info/agency.txt, no "rtap" string
      // anywhere, shapes.txt present-but-empty.
      const result = detectRtapFeed(
        FEED_INFO({ feed_publisher_name: 'Skyline Bus', feed_publisher_url: 'https://skylinebus.com/' }),
        [AGENCY({ agency_name: 'Skyline Bus', agency_url: 'https://skylinebus.com/' })],
        RTAP_STRUCTURAL_SIGNATURE,
      );
      expect(result.isRtap).toBe(true);
      expect(result.confidence).toBe('low');
    });

    it('does not fire on an ordinary feed\'s structural signature (negative control)', () => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], ORDINARY_STRUCTURAL_SIGNATURE);
      expect(result).toEqual({ isRtap: false, confidence: 'low', signals: [] });
    });

    it('does not fire when builderSignals is omitted entirely', () => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()]);
      expect(result.isRtap).toBe(false);
    });

    it.each([
      ['missing BOM', { hasUtf8Bom: false, shapesFileHeaderOnly: true, emitsAllOptionalColumns: true }],
      ['missing header-only shapes.txt', { hasUtf8Bom: true, shapesFileHeaderOnly: false, emitsAllOptionalColumns: true }],
      ['missing full optional-column set', { hasUtf8Bom: true, shapesFileHeaderOnly: true, emitsAllOptionalColumns: false }],
    ])('requires all three structural signals together — %s alone does not fire', (_label, partial) => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], partial as BuilderSignals);
      expect(result.isRtap).toBe(false);
    });

    it('keeps high confidence when both a string match and the structural signature are present', () => {
      const result = detectRtapFeed(
        FEED_INFO({ feed_publisher_name: 'National RTAP' }),
        [],
        RTAP_STRUCTURAL_SIGNATURE,
      );
      expect(result.isRtap).toBe(true);
      expect(result.confidence).toBe('high');
      expect(result.signals.length).toBeGreaterThan(1);
    });
  });
});
